/* eslint-disable @next/next/no-img-element */
import { importCatalogCard } from "@/app/catalogo/actions";
import { PokemonTcgCatalogProvider } from "@/features/catalog/pokemon-tcg-provider";

export const dynamic = "force-dynamic";

export default async function CatalogPage({ searchParams }: { searchParams: Promise<{ q?: string; error?: string; message?: string }> }) {
  const params = await searchParams;
  const query = params.q?.trim() ?? "";
  const results = query ? await new PokemonTcgCatalogProvider().search(query) : [];
  return <section className="space-y-6"><div><h1 className="text-2xl font-black">Catálogo</h1><p className="mt-2 text-sm text-slate-500">Busque uma carta nas fontes externas e importe o resultado para o seu catálogo.</p></div>{params.error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Não foi possível importar essa carta.</p>}{params.message && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Carta importada com sucesso.</p>}<form className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-4" method="get"><input className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-3" defaultValue={query} name="q" placeholder="Ex.: Pikachu, Charizard ex, 151" required /><button className="rounded-xl bg-ink px-4 py-3 font-bold text-white" type="submit">Buscar</button></form>{query && <p className="text-sm text-slate-500">{results.length} resultado(s) encontrado(s) para “{query}”.</p>}<div className="grid gap-3 sm:grid-cols-2">{results.map((card) => <article className="flex gap-3 rounded-2xl border border-slate-200 bg-white p-4" key={`${card.source}-${card.external_id}`}><div className="h-28 w-20 shrink-0 overflow-hidden rounded-lg bg-slate-100">{card.image_url && <img alt={card.name} className="h-full w-full object-cover" src={card.image_url} />}</div><div className="min-w-0 flex-1"><p className="font-bold">{card.name}</p><p className="mt-1 text-xs text-slate-500">{card.set_name ?? "Coleção desconhecida"} · {card.card_number ?? "Sem número"}</p><p className="mt-1 text-xs text-slate-500">Fonte: {card.source}</p><form action={importCatalogCard} className="mt-3"><input name="name" type="hidden" value={card.name} /><input name="card_number" type="hidden" value={card.card_number ?? ""} /><input name="set_name" type="hidden" value={card.set_name ?? ""} /><input name="language" type="hidden" value={card.language} /><input name="rarity" type="hidden" value={card.rarity ?? ""} /><input name="variant" type="hidden" value={card.variant} /><input name="image_url" type="hidden" value={card.image_url ?? ""} /><button className="rounded-lg bg-accent px-3 py-2 text-xs font-bold text-white" type="submit">Importar carta</button></form></div></article>)}{query && !results.length && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500 sm:col-span-2">Nenhuma carta encontrada. Tente outro nome ou número.</div>}</div></section>;
}
