import { addToCollection } from "@/app/colecao/actions";

export const dynamic = "force-dynamic";

export default async function CollectionPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const params = await searchParams;
  const supabase = (await import("@/lib/supabase-server")).createSupabaseServerClient;
  const client = await supabase();
  const { data: cards } = await client.from("card_catalog").select("id,name,set_name,language,variant").order("name");
  const { data: entries } = await client.from("collection_entries").select("id,quantity,language,condition,card_catalog(name,set_name)").order("created_at", { ascending: false });
  return <section className="space-y-6"><div><h1 className="text-2xl font-black">Minha coleção</h1><p className="mt-2 text-sm text-slate-500">Cartas pertencentes a você, independentemente dos fichários.</p></div>{params.error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Não foi possível adicionar a carta.</p>}{params.message && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Carta adicionada à coleção.</p>}<form action={addToCollection} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-3"><label className="text-sm font-semibold sm:col-span-2">Carta<select className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" name="card_id" required><option value="">Selecione uma carta</option>{(cards ?? []).map((card) => <option key={card.id} value={card.id}>{card.name} — {card.set_name ?? "Sem coleção"} ({card.variant})</option>)}</select></label><label className="text-sm font-semibold">Quantidade<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" defaultValue="1" min="1" name="quantity" required type="number" /></label><button className="rounded-xl bg-ink px-4 py-3 font-bold text-white sm:col-span-3" type="submit">Adicionar à coleção</button></form><div className="space-y-3">{entries?.length ? entries.map((entry) => <article className="rounded-2xl border border-slate-200 bg-white p-4" key={entry.id}><p className="font-bold">{((Array.isArray(entry.card_catalog) ? entry.card_catalog[0] : entry.card_catalog) as { name: string } | null)?.name ?? "Carta"}</p><p className="mt-1 text-sm text-slate-500">Quantidade: {entry.quantity} · Idioma: {entry.language}</p></article>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">Nenhuma carta cadastrada ainda.</div>}</div></section>;
}
