import { createPull } from "@/app/pulls/actions";

export const dynamic = "force-dynamic";

export default async function PullsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const params = await searchParams;
  const client = await (await import("@/lib/supabase-server")).createSupabaseServerClient();
  const { data: cards } = await client.from("card_catalog").select("id,name,set_name").order("name");
  const { data: pulls } = await client.from("pulls").select("id,status,shipping_cents,notes,created_at,sellers(name),pull_items(quantity,unit_price_cents,card_catalog(name))").order("created_at", { ascending: false });
  return <section className="space-y-6"><div><h1 className="text-2xl font-black">Pulls</h1><p className="mt-2 text-sm text-slate-500">Acompanhe compras privadas e confirme cartas somente após a entrega.</p></div>{params.error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Não foi possível criar o Pull.</p>}{params.message && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Pull criado com sucesso.</p>}<form action={createPull} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><label className="text-sm font-semibold">Vendedor<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" name="seller_name" required /></label><label className="text-sm font-semibold">Carta<select className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" name="card_id" required><option value="">Selecione</option>{(cards ?? []).map((card) => <option key={card.id} value={card.id}>{card.name} — {card.set_name ?? "Sem coleção"}</option>)}</select></label><label className="text-sm font-semibold">Quantidade<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" defaultValue="1" min="1" name="quantity" required type="number" /></label><label className="text-sm font-semibold">Valor unitário (centavos)<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" min="0" name="unit_price_cents" required type="number" /></label><label className="text-sm font-semibold">Frete (centavos)<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" defaultValue="0" min="0" name="shipping_cents" required type="number" /></label><label className="text-sm font-semibold">Observações<textarea className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" name="notes" /></label><button className="rounded-xl bg-ink px-4 py-3 font-bold text-white sm:col-span-2" type="submit">Registrar Pull</button></form><div className="space-y-3">{pulls?.length ? pulls.map((pull) => <article className="rounded-2xl border border-slate-200 bg-white p-4" key={pull.id}><p className="font-bold">{(Array.isArray(pull.sellers) ? pull.sellers[0] : pull.sellers)?.name ?? "Vendedor"}</p><p className="mt-1 text-sm text-slate-500">Status: {pull.status} · Frete: {pull.shipping_cents} centavos</p></article>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">Nenhum Pull registrado ainda.</div>}</div></section>;
}
