"use client";

import Link from "next/link";
import { useState } from "react";

type Section = "home" | "binders" | "trades" | "profile";
type Modal = "card" | "binder" | "offer" | "friend" | "profile" | null;

const cards = [
  { name: "Pikachu", set: "151 · #025", color: "#f1bd25", initials: "P", status: "Disponível" },
  { name: "Mew ex", set: "151 · #193", color: "#a884d7", initials: "M", status: "Disponível" },
  { name: "Charizard", set: "Obsidiana · #125", color: "#e7693d", initials: "C", status: "Em oferta" },
  { name: "Eevee", set: "Evoluções · #062", color: "#b98961", initials: "E", status: "Disponível" },
  { name: "Gengar", set: "Crepúsculo · #057", color: "#7959a9", initials: "G", status: "Desejo" },
  { name: "Bulbasaur", set: "151 · #001", color: "#5ea276", initials: "B", status: "Disponível" },
];

const binders = [
  { name: "Coleção principal", count: 96, pages: 12, color: "#d92735" },
  { name: "Favoritos", count: 32, pages: 4, color: "#f0b52f" },
  { name: "Trocas 2026", count: 18, pages: 3, color: "#7198c8" },
];

function ModalFrame({ title, description, onClose, children }: { title: string; description?: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal-card p-5 sm:p-6" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black tracking-tight">{title}</h2>{description && <p className="mt-1 text-sm muted">{description}</p>}</div><button aria-label="Fechar" className="secondary-button !rounded-full !p-2" onClick={onClose}>×</button></div>{children}</div></div>;
}

function CardTile({ card, onClick }: { card: (typeof cards)[number]; onClick?: () => void }) {
  return <button className="group text-left" onClick={onClick}><div className="relative aspect-[0.72] overflow-hidden rounded-xl border-4 bg-white p-2 shadow-sm transition group-hover:-translate-y-1 group-hover:shadow-md" style={{ borderColor: card.color }}><div className="flex h-full flex-col justify-between rounded-lg p-2" style={{ background: `linear-gradient(145deg, ${card.color}2b, #fff)` }}><div className="flex items-start justify-between"><span className="text-[10px] font-black">{card.name}</span><span className="rounded-full bg-white/80 px-1.5 py-0.5 text-[9px] font-black">HP</span></div><div className="flex flex-1 items-center justify-center"><span className="text-4xl font-black opacity-30">{card.initials}</span></div><div><p className="text-[9px] font-bold text-slate-600">{card.set}</p><div className="mt-1 h-1 rounded-full bg-black/10"><div className="h-full w-2/3 rounded-full" style={{ backgroundColor: card.color }} /></div></div></div></div><p className="mt-2 truncate text-xs font-black">{card.name}</p><p className="text-[10px] muted">{card.status}</p></button>;
}

function AppModal({ modal, close }: { modal: Modal; close: () => void }) {
  if (!modal) return null;
  if (modal === "card") return <ModalFrame title="Adicionar carta" description="Encontre uma carta ou registre uma cópia manualmente." onClose={close}><div className="mt-5 space-y-3"><label className="block text-sm font-bold">Buscar carta<input className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 outline-none focus:border-red-400" placeholder="Nome, coleção ou número" /></label><div className="grid grid-cols-3 gap-2">{cards.slice(0, 3).map((card) => <CardTile card={card} key={card.name} onClick={close} />)}</div><button className="primary-button w-full" onClick={close}>Adicionar à minha coleção</button></div></ModalFrame>;
  if (modal === "binder") return <ModalFrame title="Novo fichário" description="Crie um espaço para organizar suas cartas." onClose={close}><div className="mt-5 space-y-3"><label className="block text-sm font-bold">Nome<input className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3" defaultValue="Meu novo fichário" /></label><label className="block text-sm font-bold">Quantidade de páginas<input className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3" defaultValue="4" type="number" /></label><label className="block text-sm font-bold">Visibilidade<select className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3"><option>Privado</option><option>Compartilhado por link</option></select></label><button className="primary-button w-full" onClick={close}>Criar fichário</button></div></ModalFrame>;
  if (modal === "offer") return <ModalFrame title="Fazer oferta" description="Monte uma proposta para trocar cartas com outro colecionador." onClose={close}><div className="mt-5 space-y-4"><div><p className="mb-2 text-sm font-black">Você oferece</p><div className="grid grid-cols-4 gap-2">{cards.slice(0, 4).map((card) => <CardTile card={card} key={card.name} onClick={() => undefined} />)}</div></div><div><p className="mb-2 text-sm font-black">Você deseja receber</p><div className="flex gap-2 overflow-x-auto pb-1">{cards.slice(1, 4).map((card) => <button className="min-w-28 rounded-xl border border-dashed border-red-200 p-3 text-center text-xs font-bold text-red-600" key={card.name}>{card.name}<br /><span className="text-[10px] font-normal text-slate-400">+ adicionar</span></button>)}</div></div><button className="primary-button w-full" onClick={close}>Enviar proposta</button></div></ModalFrame>;
  if (modal === "friend") return <ModalFrame title="Adicionar amigo" description="Encontre colecionadores pelo nome de usuário." onClose={close}><div className="mt-5 space-y-3"><label className="block text-sm font-bold">Nome de usuário<input className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3" placeholder="ex.: treinador_ash" /></label><div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Você decide quais fichários e cartas deseja compartilhar.</div><button className="primary-button w-full" onClick={close}>Enviar solicitação</button></div></ModalFrame>;
  return <ModalFrame title="Editar perfil" description="Atualize as informações que seus amigos verão." onClose={close}><div className="mt-5 space-y-3"><label className="block text-sm font-bold">Nome<input className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3" defaultValue="Guilherme" /></label><label className="block text-sm font-bold">Nome de usuário<input className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3" defaultValue="guicamarg0" /></label><button className="primary-button w-full" onClick={close}>Salvar alterações</button></div></ModalFrame>;
}

function QuickAction({ icon, title, text, href }: { icon: string; title: string; text: string; href: string }) { return <Link className="flex items-center gap-4 rounded-2xl border border-slate-100 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-red-100" href={href}><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-red-50 text-xl text-red-600">{icon}</span><span><strong className="block text-sm font-black">{title}</strong><span className="mt-1 block text-xs muted">{text}</span></span><span className="ml-auto text-xl text-slate-300">›</span></Link>; }
function SectionHeader({ title, action, href }: { title: string; action: string; href: string }) { return <div className="mb-3 flex items-center justify-between"><h2 className="section-title">{title}</h2><Link className="text-sm font-black text-red-600" href={href}>{action} ›</Link></div>; }
function Activity({ label, text, tone }: { label: string; text: string; tone: string }) { return <div className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><span className={`inline-block h-2 w-2 rounded-full bg-${tone === "red" ? "red" : tone === "yellow" ? "amber" : "blue"}-400`} /><p className="mt-2 text-xs font-black">{label}</p><p className="mt-1 text-xs leading-5 muted">{text}</p></div>; }
function BinderMini({ binder }: { binder: (typeof binders)[number] }) { return <Link href="/ficharios" className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="binder-cover" style={{ backgroundColor: binder.color }}><div className="mini-pokeball" /></div><p className="mt-3 text-sm font-black">{binder.name}</p><p className="mt-1 text-xs muted">{binder.count} cartas · {binder.pages} páginas</p></Link>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-red-100 text-xs font-black text-red-600">{number}</span><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs leading-5 muted">{text}</p></div></div>; }
function Toggle({ label, active = false }: { label: string; active?: boolean }) { const [on, setOn] = useState(active); return <button className="flex w-full items-center justify-between rounded-xl border border-slate-100 p-3 text-left text-sm font-bold" onClick={() => setOn(!on)}><span>{label}</span><span className={`toggle ${on ? "toggle-on" : ""}`}><span /></span></button>; }

function Home({ open }: { open: (modal: Modal) => void }) {
  return <section className="space-y-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-red-600">Bom dia, Guilherme 👋</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">O que vamos organizar?</h1></div><button className="secondary-button hidden sm:inline-flex" onClick={() => open("card")}>＋ Carta</button></div><div className="soft-panel overflow-hidden rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-col items-start gap-6 sm:flex-row sm:items-center"><div className="pokeball-mark"><div /></div><div className="flex-1"><p className="text-sm font-bold muted">Resumo da sua coleção</p><div className="mt-2 flex items-baseline gap-5"><strong className="text-4xl font-black text-red-600">128</strong><span className="text-sm font-bold muted">cartas</span><span className="h-8 w-px bg-red-100" /><strong className="text-4xl font-black text-red-600">3</strong><span className="text-sm font-bold muted">fichários</span></div><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Grandes coleções começam com uma única carta.</p></div><button className="primary-button w-full sm:w-auto" onClick={() => open("card")}>＋ Adicionar carta</button></div></div><div className="grid gap-3 sm:grid-cols-3"><QuickAction icon="▣" title="Meus fichários" text="Organize suas páginas" href="/ficharios" /><QuickAction icon="⇄" title="Trocar cartas" text="Encontre sua próxima carta" href="/trocas" /><QuickAction icon="♙" title="Adicionar amigos" text="Colecione em comunidade" href="/perfil" /></div><section><SectionHeader title="Atividade recente" action="Ver trocas" href="/trocas" /><div className="grid gap-3 sm:grid-cols-3"><Activity label="Nova oferta recebida" text="Marina quer trocar Charizard por Mew ex" tone="red" /><Activity label="Carta adicionada" text="Pikachu foi para Coleção principal" tone="yellow" /><Activity label="Novo amigo" text="Você e Lucas agora são amigos" tone="blue" /></div></section><section><SectionHeader title="Seus fichários" action="Ver todos" href="/ficharios" /><div className="grid gap-3 sm:grid-cols-3">{binders.map((binder) => <BinderMini binder={binder} key={binder.name} />)}</div></section></section>;
}

function Binders({ open }: { open: (modal: Modal) => void }) { return <section className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-red-600">Sua organização</p><h1 className="mt-1 text-3xl font-black tracking-tight">Meus fichários</h1><p className="mt-2 text-sm muted">Cada carta no seu lugar, do seu jeito.</p></div><button className="primary-button" onClick={() => open("binder")}>＋ Novo fichário</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{binders.map((binder) => <article className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm" key={binder.name}><div className="binder-hero" style={{ background: `linear-gradient(135deg, ${binder.color}, #fff 140%)` }}><div className="large-pokeball" /><span className="rounded-full bg-white/80 px-3 py-1 text-xs font-black text-slate-700">3 × 3</span></div><div className="p-5"><div className="flex items-start justify-between"><div><h2 className="font-black">{binder.name}</h2><p className="mt-1 text-xs muted">{binder.count} cartas · {binder.pages} páginas</p></div><button className="text-xl text-slate-400">⋮</button></div><div className="mt-4 flex gap-2"><Link className="secondary-button flex-1" href="/ficharios">Abrir fichário</Link><button className="primary-button !px-4" onClick={() => open("card")}>＋</button></div></div></article>)}<button className="flex min-h-[16rem] flex-col items-center justify-center rounded-3xl border-2 border-dashed border-red-100 bg-red-50/30 p-5 text-center" onClick={() => open("binder")}><span className="flex h-14 w-14 items-center justify-center rounded-full bg-white text-3xl text-red-500 shadow-sm">＋</span><strong className="mt-4 text-sm font-black">Criar novo fichário</strong><span className="mt-1 text-xs muted">Comece uma nova organização</span></button></div><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-black">Como funciona?</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Step number="1" title="Crie" text="Dê um nome e escolha o tamanho." /><Step number="2" title="Organize" text="Mova cartas entre páginas 3 × 3." /><Step number="3" title="Compartilhe" text="Convide amigos para ver ou colaborar." /></div></div></section>; }

function Trades({ open }: { open: (modal: Modal) => void }) { return <section className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-red-600">Encontre sua próxima carta</p><h1 className="mt-1 text-3xl font-black tracking-tight">Trocas</h1><p className="mt-2 text-sm muted">Ofereça o que você tem e encontre o que deseja.</p></div><button className="primary-button" onClick={() => open("offer")}>＋ Fazer oferta</button></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-red-600 p-5 text-white"><p className="text-3xl font-black">12</p><p className="mt-1 text-sm text-red-100">cartas ofertadas</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-3xl font-black text-red-600">4</p><p className="mt-1 text-sm muted">ofertas recebidas</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-3xl font-black text-red-600">8</p><p className="mt-1 text-sm muted">cartas desejadas</p></div></div><div className="flex gap-2 overflow-x-auto pb-1"><button className="rounded-full bg-red-600 px-4 py-2 text-xs font-black text-white">Explorar ofertas</button><button className="rounded-full bg-white px-4 py-2 text-xs font-black text-slate-500 shadow-sm">Minhas cartas</button><button className="rounded-full bg-white px-4 py-2 text-xs font-black text-slate-500 shadow-sm">Lista de desejos</button></div><section><SectionHeader title="Ofertas para você" action="Filtrar" href="/trocas" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[{ user: "Marina Costa", avatar: "MC", wants: "Mew ex", offers: "Charizard", color: "#e7693d" }, { user: "Lucas TCG", avatar: "LT", wants: "Pikachu", offers: "Eevee + 1 carta", color: "#b98961" }, { user: "Ana Coleciona", avatar: "AC", wants: "Gengar", offers: "3 cartas da coleção 151", color: "#7959a9" }].map((offer) => <article className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm" key={offer.user}><div className="flex items-center gap-3"><span className="avatar">{offer.avatar}</span><div><p className="text-sm font-black">{offer.user}</p><p className="text-xs muted">há 2 horas · perto de você</p></div></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div><div className="trade-card" style={{ borderColor: offer.color }}><span>{offer.wants[0]}</span></div><p className="mt-2 text-center text-xs font-black">Quer {offer.wants}</p></div><span className="text-2xl font-black text-red-500">⇄</span><div><div className="trade-card" style={{ borderColor: "#d92735" }}><span>{offer.offers[0]}</span></div><p className="mt-2 text-center text-xs font-black">Oferece {offer.offers}</p></div></div><button className="secondary-button mt-5 w-full" onClick={() => open("offer")}>Ver oferta</button></article>)}</div></section></section>; }

function Profile({ open }: { open: (modal: Modal) => void }) { return <section className="space-y-7"><div className="soft-panel flex flex-col items-center gap-4 rounded-3xl p-6 text-center sm:flex-row sm:text-left"><div className="profile-avatar">G</div><div className="flex-1"><p className="text-2xl font-black">Guilherme Camargo</p><p className="mt-1 text-sm muted">@guicamarg0 · colecionador desde 2026</p><div className="mt-3 flex justify-center gap-5 text-xs sm:justify-start"><span><strong className="block text-lg font-black">128</strong><span className="muted">cartas</span></span><span><strong className="block text-lg font-black">3</strong><span className="muted">fichários</span></span><span><strong className="block text-lg font-black">12</strong><span className="muted">amigos</span></span></div></div><button className="secondary-button" onClick={() => open("profile")}>Editar perfil</button></div><div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="section-title">Meus amigos</h2><button className="text-sm font-black text-red-600" onClick={() => open("friend")}>＋ Adicionar</button></div><div className="mt-5 space-y-3">{[{ name: "Marina Costa", handle: "@marina.cards", avatar: "MC", status: "online" }, { name: "Lucas TCG", handle: "@lucastcg", avatar: "LT", status: "há 5 min" }, { name: "Ana Coleciona", handle: "@anacoleciona", avatar: "AC", status: "há 1 h" }].map((friend) => <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3" key={friend.handle}><span className="avatar">{friend.avatar}</span><div className="flex-1"><p className="text-sm font-black">{friend.name}</p><p className="text-xs muted">{friend.handle}</p></div><span className="text-[10px] font-bold text-slate-400">{friend.status}</span></div>)}</div></section><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="section-title">Privacidade</h2><p className="mt-2 text-sm leading-6 muted">Controle o que seus amigos e a comunidade podem ver.</p><div className="mt-4 space-y-3"><Toggle label="Perfil público" active /><Toggle label="Aceitar ofertas de troca" active /><Toggle label="Mostrar atividade recente" /></div></section></div><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="section-title">Preferências</h2><div className="mt-4 grid gap-2 sm:grid-cols-3"><button className="preference-button">⌄ Aparência <span>Claro</span></button><button className="preference-button">◉ Notificações <span>Ativas</span></button><button className="preference-button">⚙ Conta <span>Configurações</span></button></div></section></section>; }

export function PokeBinderPrototype({ section }: { section: Section }) { const [modal, setModal] = useState<Modal>(null); const content = section === "home" ? <Home open={setModal} /> : section === "binders" ? <Binders open={setModal} /> : section === "trades" ? <Trades open={setModal} /> : <Profile open={setModal} />; return <><AppModal modal={modal} close={() => setModal(null)} />{content}</>; }
